// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    hover_tags();
    return placeholder_text();
  });

  window.hover_tags = function() {
    $('body').on('mouseover', '[data-hover-tag]', function(e) {
      var left_offset, name, old_title, pointer_styles, position, tag, tag_styles, target, top_offset;
      target = $(this).closest('[data-hover-tag]');
      old_title = target.attr('title');
      target.attr('title', '');
      name = unescape(target.data('hover-tag'));
      if (name === '') {
        name = old_title;
        target.data('hover-tag', old_title);
      }
      position = target.offset();
      if ($('.hover_tag').length === 0) {
        tag_styles = {
          position: 'absolute',
          display: 'none',
          padding: '4px 6px 2px',
          background: 'black',
          background: 'rgba(0,0,0,0.8)',
          color: 'white',
          fontSize: '13px',
          textTransform: 'lowercase',
          zIndex: 800
        };
        pointer_styles = {
          position: 'absolute',
          top: '-6px',
          left: '50%',
          marginLeft: '-3px',
          width: '8px',
          height: '6px',
          background: 'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAYAAAD+Bd/7AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAElJREFUeNpiYEAFxVCMFRgD8RkoNoYJMkJpXiBeBsSSUP5zII4C4s/MUIFcILZEMg2kgR2IjzNCjZuJw9p0kILNSEajg+cAAQYA1jkKUj6WaH4AAAAASUVORK5CYII=) no-repeat'
        };
        $('body').append("        <div class='hover_tag'>          <div class='text'></div>          <div class='tag_pointer'></div>        </div>");
        $('.hover_tag').css(tag_styles);
        $('.hover_tag .tag_pointer').css(pointer_styles);
      }
      tag = $('.hover_tag');
      tag.find('.text').html(name);
      top_offset = 8;
      left_offset = 0;
      return tag.css({
        top: position.top + target.outerHeight() + top_offset,
        left: position.left - tag.outerWidth() / 2 + target.width() / 2 + left_offset
      }).show();
    });
    return $('body').on('mouseout', '[data-hover-tag]', function(e) {
      return $('.hover_tag').hide();
    });
  };

  window.set_placeholder_text = function() {
    if (typeof Modernizer === "undefined" || Modernizer === null) {
      return;
    }
    if (!Modernizr.input.placeholder) {
      $('[placeholder]').focus(function() {
        var input;
        input = $(this);
        if (input.val() === input.attr('placeholder')) {
          input.val('');
          return input.removeClass('placeholder');
        }
      }).blur(function() {
        var input;
        input = $(this);
        if (input.val() === '' || input.val() === input.attr('placeholder')) {
          input.addClass('placeholder');
          return input.val(input.attr('placeholder'));
        }
      }).blur();
      return $('[placeholder]').parents('form').submit(function() {
        return $(this).find('[placeholder]').each(function() {
          var input;
          input = $(this);
          if (input.val() === input.attr('placeholder')) {
            return input.val('');
          }
        });
      });
    }
  };

  jQuery.fn.autoexpand = function(on_change, force) {
    var elements,
      _this = this;
    if (on_change == null) {
      on_change = false;
    }
    if (force == null) {
      force = false;
    }
    if (!$('html').hasClass('ie8')) {
      elements = $(this);
      return elements.each(function(i, textarea) {
        var interval, observer, oldValue;
        textarea = $(textarea);
        interval = null;
        oldValue = textarea.val();
        observer = function() {
          var char_per_line, current_length, lines, newValue, returns, _ref;
          newValue = textarea.val();
          if (newValue !== oldValue) {
            char_per_line = textarea.width() / 6;
            current_length = newValue.length;
            lines = Math.floor(current_length / char_per_line);
            returns = ((_ref = newValue.match(/\n/g)) != null ? _ref.length : void 0) || 0;
            textarea.attr('rows', lines + returns + 2);
            oldValue = newValue;
            if (on_change) {
              return on_change();
            }
          }
        };
        textarea.focus(function() {
          return interval = setInterval(observer, 250);
        });
        textarea.blur(function() {
          return clearInterval(interval);
        });
        if (force) {
          return textarea.focus();
        }
      });
    }
  };

  jQuery.fn.square_image = function() {
    var h, img, larger, percent, smaller, w, wrapper;
    img = $(this);
    wrapper = img.parent();
    w = img.width();
    h = img.height();
    img.css({
      position: 'absolute'
    });
    if (w < h) {
      smaller = w;
      larger = h;
    } else {
      smaller = h;
      larger = w;
    }
    percent = (((larger - smaller) / 2) * 100 / larger * -1) / 100;
    if (h > w) {
      img.css({
        width: '100%',
        height: 'auto'
      });
      return img.css({
        top: Math.floor(percent * img.height())
      });
    } else if (h < w) {
      img.css({
        width: 'auto',
        height: '100%'
      });
      return img.css({
        left: Math.floor(percent * img.width())
      });
    } else {
      return img.css({
        width: '100%',
        height: '100%'
      });
    }
  };

  jQuery.fn.save_state = function() {
    var saving_text;
    saving_text = $(this).attr('data-saving-text');
    $(this).addClass('saving').css({
      opacity: 0.5
    });
    if ($(this).is('a')) {
      return $(this).text(saving_text);
    } else {
      return $(this).val(saving_text);
    }
  };

  jQuery.fn.unsave_state = function() {
    var saving_text;
    saving_text = $(this).attr('data-original-text');
    $(this).addClass('saving').css({
      opacity: 0.5
    });
    if ($(this).is('a')) {
      return $(this).text(saving_text);
    } else {
      return $(this).val(saving_text);
    }
  };

  jQuery.fn.link_urls = function() {
    return $(this).each(function() {
      var exp,
        _this = this;
      if (!$(this).hasClass('autolinked')) {
        exp = /\b(?:(?:https?|ftp|file):\/\/|www\.|ftp\.)(?:\([-A-Z0-9+&@\#\/%=~_|$?!:,.]*\)|[-A-Z0-9+&@\#\/%=~_|$?!:,.])*(?:\([-A-Z0-9+&@\#\/%=~_|$?!:,.]*\)|[A-Z0-9+&@\#\/%=~_|$])/ig;
        _($(this).text().match(exp)).each(function(url) {
          var href, visual_url;
          href = url.match(/^www.+/) ? "http://" + url : url;
          visual_url = url.split('').join('&#8203;').replace(/(^.{300}).+/, '$1...');
          return $(_this).html($(_this).html().replace(/\&amp\;/g, '&').replace(url, "<a href='" + href + "' target='_blank'>" + visual_url + "</a>"));
        });
        return $(this).addClass('autolinked');
      }
    });
  };

  window.set_tabindex = function(items) {
    $('[tabindex]').removeAttr('tabindex');
    return _.each(items, function(item, i) {
      return $(item).attr('tabindex', i + 1);
    });
  };

  jQuery.fn.outerHTML = function() {
    return $(this).clone().wrap('<div>').parent().html();
  };

  window.should_allow_keyboard_shortcuts = function() {
    if ($(':focus').is('input') || $(':focus').is('textarea') || $(':focus').is('select') || $('html').hasClass('ie8')) {
      return false;
    } else {
      return true;
    }
  };

}).call(this);
