// Generated by CoffeeScript 1.4.0
(function() {
  var set_autoexpand, set_autolink, set_center_image, set_kb, set_outerhtml, set_square_image, set_tabindex;

  $(window).load(function() {
    hover_tags();
    set_placeholder_text();
    set_autoexpand();
    set_square_image();
    set_center_image();
    set_autolink();
    set_tabindex();
    set_outerhtml();
    return set_kb();
  });

  set_autoexpand = function() {
    return $('#autoexpand textarea').autoexpand();
  };

  set_square_image = function() {
    return $('#square_image_wrapper').square_image();
  };

  set_center_image = function() {
    return $('#center_image_wrapper').center_image();
  };

  set_autolink = function() {
    return $('#to_autolink').link_urls();
  };

  set_tabindex = function() {
    return window.set_tabindex([$('.tabindex1'), $('.tabindex2'), $('.tabindex3'), $('.tabindex4')]);
  };

  set_outerhtml = function() {
    console.log($('#to_outerhtml').html());
    return console.log($('#to_outerhtml').outerHTML());
  };

  set_kb = function() {
    var inputs;
    inputs = $('#keyboard_shortcuts input, #keyboard_shortcuts textarea');
    inputs.on('focus', function() {
      return console.log(window.should_allow_keyboard_shortcuts());
    });
    return inputs.on('blur', function() {
      return console.log(window.should_allow_keyboard_shortcuts());
    });
  };

}).call(this);
